---
  
   - name: Instalamos el operador de Tigera
     become: yes
     command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

  #  - name: Descargamos el fichero de definición
  #    become: yes
  #    command: wget https://docs.projectcalico.org/manifests/custom-resources.yaml

   - name: Copy custom-resources.yaml
     template:
       src: custom-resources.j2
       dest: /tmp/custom-resources.yaml

   - name: Instalamos Calico
     become: yes
     command: kubectl apply -f /tmp/custom-resources.yaml