---
  
   - name: Enable NFS
     service:
       name: nfs-server
       state: started
       enabled: yes

   - name: Creando dir 
     file:
       path: /srv/nfs
       state: directory

   - name: Configurando share nfs
     copy:
      src: ficheros/exports
      dest: /etc/exports
      mode: u=rw,g=r,o=r

   - name: Aplicando config nfs 
     become: yes
     command: exportfs -r

   - name: Aplicando config nfs 
     become: yes
     command: exportfs -s

   - name: Abriendo puertos para el nfs 
     become: yes
     command: firewall-cmd --permanent --add-service=nfs

   - name: Abriendo puertos para el nfs 
     become: yes
     command: firewall-cmd --permanent --add-service=rpc-bind

   - name: Abriendo puertos para el nfs 
     become: yes
     command: firewall-cmd --permanent --add-service=mountd

   - name: Reload Firewall 
     become: yes
     command: firewall-cmd --reload
