---
  
   - name: Enable NFS
     service:
       name: nfs-server
       state: started
       enabled: yes

   - name: Creando dir 
     file:
       path: /srv/nfs
       state: directory

   - name: Configurando share nfs
     copy:
      src: ficheros/exports
      dest: /etc/exports
      mode: u=rw,g=r,o=r

# En teoría con el become somos superusuarios, pero sin añadir el 
# sudo no he logrado hacerlo funcionar. Puedes probarlo, sin  el sudo me dice
# que extra arguments are not permitted with -a or -r
   - name: Aplicando config nfs 
     become: yes
     command: sudo exportfs -r | sudo exportfs -s

   - name: Abriendo puertos para el nfs 
     become: yes
     command: firewall-cmd --permanent --add-service=nfs | 
              firewall-cmd --permanent --add-service=rpc-bind | 
              firewall-cmd --permanent --add-service=mountd |
              firewall-cmd --reload