---
  
   - name: Enable NFS
     service:
       name: nfs-server
       state: started
       enabled: yes

   - name: Creando dir /srv/nfs
     file:
       path: /srv/nfs
       state: directory

   - name: Configurando share nfs
     copy:
      src: ficheros/exports
      dest: /etc/exports
      mode: u=rw,g=r,o=r

   - name: Aplicando config nfs 
     become: yes
     command: exportfs -r

   - name: Aplicando config nfs 
     become: yes
     command: exportfs -s

# Started solo lo inicia si no está ya iniciado
   - name: Activar Firewalld
     service:
       name: firewalld
       state: started
       enabled: yes

   - name: Abriendo puertos para el nfs 
     firewalld: 
       service: "{{ item }}"
       permanent: true
       state: enabled
     loop:
       - nfs
       - rpc-bind
       - mountd

# reloaded mejor que restarted para que recargue la configuración
   - name: Reload Firewall 
     service:
       name: firewalld
       state: reloaded
       enabled: yes
