---
  
  - name: Creamos un nuevo token para el Cluster-Join
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Mostramos comando
    debug:
      msg: "{{ join_command.stdout }}"
  
  - debug:
      var: join_command
  
  - name: set join command
    set_fact:
      join_command: "{{ join_command.stdout_lines[0] }}"

